# Generated by Django 5.2.8 on 2025-11-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=10)),
                ('packet_size', models.IntegerField()),
                ('prediction', models.CharField(blank=True, max_length=50)),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
    ]
